_deploy: &_deploy
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  skip_cleanup: true
  file_glob: true
  file: build/*-dist.zip
  on: &_deploy_on
    tags: true
    jdk: oraclejdk8

language: java
install: true

jdk:
  - oraclejdk8
  - oraclejdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - script: ./gradlew check --stacktrace
    - stage: GitHub Release
      script: ./gradlew release
      before_deploy:
        - export PROJECT_VERSION=$(gradle -q printVersion)
      deploy:
        - <<: *_deploy
          prerelease: true
          draft: true
          name: "Preview test release ${PROJECT_VERSION}"
          on:
            <<: *_deploy_on
            branch: release-test
        - <<: *_deploy
          prerelease: true
          name: "Preview release ${PROJECT_VERSION}"
          on:
            <<: *_deploy_on
            all_branches: true
            condition: $TRAVIS_TAG =~ /^preview[/-]/
        - <<: *_deploy
          prerelease: true
          name: "${PROJECT_VERSION}"
          on:
            <<: *_deploy_on
            branch: master
            condition: $PROJECT_VERSION =~ /SNAPSHOT/
        - <<: *_deploy
          name: "${PROJECT_VERSION}"
          on:
            <<: *_deploy_on
            branch: master
            condition: $PROJECT_VERSION !~ /SNAPSHOT/
